import { describe, expect, it } from 'vitest'
import { createSmartMemoryExtractor } from './smart-memory-extractor'
import type { GraphExtractionRun } from './graph-extraction-result'

describe('smart extractor graph capture', () => {
  it('retains an open relation generated by the configured extractor without applying the predicate registry', async () => {
    const saved: GraphExtractionRun[] = []
    const source = '晶体A外延生长于衬底B'
    const raw = { memories: [], graph: { entities: [
      { id: 'a', type: 'crystal', text: '晶体A', span: { start: 0, end: 3 }, modelScore: 0.9 },
      { id: 'b', type: 'substrate', text: '衬底B', span: { start: 8, end: 11 }, modelScore: 0.9 }], facts: [],
      assertions: [{ id: 'a1', relationText: '外延生长于', relationSpan: { start: 3, end: 8 },
        participants: [{ mentionId: 'a', role: 'subject' }, { mentionId: 'b', role: 'substrate' }],
        evidenceSpan: { start: 0, end: 11 }, modelScore: 0.9 }] } }
    const extractor = createSmartMemoryExtractor({ getConfig: () => ({ apiKey: 'test', model: 'fixture' }),
      complete: async prompt => {
        expect(prompt).toContain('assertions:')
        expect(prompt).toContain('memories 的长期事实筛选标准不限制 graph.assertions')
        expect(prompt).toContain('不用于推导新的事实')
        return JSON.stringify(raw)
      },
      saveGraphExtraction: run => { saved.push(run) } })
    await extractor({ userMessage: source, assistantMessage: '', metadata: { sourceMessageIds: ['m1'] } })
    expect(saved[0]).toMatchObject({ status: 'complete', assertionCandidates: [{ relationText: '外延生长于' }] })
  })
  it('saves the complete model structure before memory conversion', async () => {
    const saved: GraphExtractionRun[] = []
    const raw = { memories: [], graph: { entities: [
      { id: 'e1', type: 'person', text: 'Alice', span: { start: 0, end: 5 }, modelScore: 0.4 },
    ], facts: [] } }
    const extractor = createSmartMemoryExtractor({
      getConfig: () => ({ apiKey: 'test', model: 'uie-test' }),
      complete: async () => JSON.stringify(raw),
      saveGraphExtraction: run => { saved.push(run) },
    })
    await extractor({ userMessage: 'Alice', assistantMessage: '', metadata: { sourceMessageIds: ['m1'] } })
    expect(saved).toHaveLength(1)
    expect(saved[0]).toMatchObject({ sourceId: 'm1', modelId: 'uie-test', status: 'complete' })
    expect(saved[0]?.rawOutput).toEqual(raw)
    expect(saved[0]?.entityMentions[0]?.modelScore).toBe(0.4)
  })

  it('records failed model output and falls back to local extraction', async () => {
    const saved: GraphExtractionRun[] = []
    const extractor = createSmartMemoryExtractor({
      getConfig: () => ({ apiKey: 'test', model: 'uie-test' }),
      complete: async () => '{broken',
      fallback: () => [{ content: 'local fact', metadata: { kind: 'explicit' } }],
      saveGraphExtraction: run => { saved.push(run) },
    })
    expect(await extractor({ userMessage: 'Alice', assistantMessage: '' })).toHaveLength(1)
    expect(saved).toMatchObject([{ status: 'failed', statusReason: 'model-or-response-error', rawOutput: '{broken' }])
  })
})
